spring:
  application:
    name: personal-finance-tracker
  jpa:
    show-sql: true
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info